[package]
name = "pubfun"
version = "0.1.0"
edition = "2024"

[dependencies]
glob = "0.3.2"
regex = "1.11.1"
tree-sitter = "0.22"
tree-sitter-kotlin = "0.3.8"
itertools = "0.14"

[build-dependencies]
cc="*"
